import Head from "next/head";
import { motion as m } from "framer-motion";
import Navbar from "../Navbar/Navbar";
import Footer from "../Footer/Footer";

export default function Layout({ children, footer, navigation }) {
  return (
    <m.div
      initial={{ opacity: 0, y: "100%" }}
      animate={{ opacity: 1, y: "0%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
    >
      <Head>
        <title>Dannach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar navigation={navigation} />
      <main>{children}</main>
      <Footer footer={footer} />
    </m.div>
  );
}
